[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build.environment]
  MONGODB_URI = "mongodb+srv://deekshajat95:MkAFXoykf1fDfdSP@cluster-mern.ideiq5j.mongodb.net/?retryWrites=true&w=majority&appName=CLUSTER-MERN"
  JWT_SECRET = "your-super-secret-key-123"
  NODE_ENV = "production"
  REACT_APP_API_URL = "your_render_backend_url"
  FRONTEND_URL = "https://bespoke-shortbread-d8df1f.netlify.app/"